site_name: Run Monopogen
repo_url: https://github.com/CyrusWang57/run_monopogen_doc
site_author: "Chunyi Wang"
# copyright: "Copyright &copy; 2023, School of Life Sciences, Westlake University"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  Language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to Light mode
      primary: teal
      accent: lime

nav:
- Homepage: index.md
- Debug and refinement: Debug.md
- Issue about formula: Formula.md
- Parameters: Parameters.md
- Results: Results.md
plugins:
  - search
  - table-reader
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js